### ISSUE TITLE
1.1.2_x64 not installing correctly

### ISSUE THREAD

**Issue by Stefanie80** [OpenBazaar/OpenBazaar-Installer#35] opened 2016-04-08 11:49 UTC
I have downloaded the new version today, but when i run the file, it just tries to start up and doesn't install properly. It shows up as installed on windows however.
But the client does not connect to local server.
It starts 3 processes, alls saying "Electron" in the description. That makes me believe that the server doesn't get started.
My system is win7_x64
last working version was 1.0.8.

**Comment by ghost** [comment] 2016-04-10 00:19
Same issue here.  1.1.1 was working nicely, then I upgraded and now I can not connect to my account.  I tried re-installing it several times.

I ended up uninstalling it from my machine and saving my appdata/roaming folder hoping the issue is resolved in another release.

**Comment by hoffmabc** [comment] 2016-04-10 00:24
Please install latest OpenSSL and it should work.

**Closed as completed by hoffmabc** 2016-04-10 00:25 UTC

**Comment by Stefanie80** [comment] 2016-04-11 07:02
Installing OpenSSL worked for me.
It was a bit of a hassle to find an Installer though.
I only found this link to a german site: http://www.heise.de/download/openssl-1122987.html
Might help someone
